<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3edce710-d4b2-427c-8133-c8eb92a40cb0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="FormattedStrings.restext" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas\Atlas.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="FormattedStrings.restext" />
  </ItemGroup>

</Project>
